version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:  
    commands: 
      - echo Starting pre-build phase
      - java -version
  build:
    commands:
      - echo Build started on `date`
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - ls
      - aws lambda update-function-code --function-name chapter_12_lambda_function --zip-file fileb://target/aws-lambda-pipeline-1.0-SNAPSHOT.jar
artifacts:
  files:
    - target/aws-lambda-pipeline*.jar
    - appspec.yml
  discard-paths: yes