apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: aws-code-pipeline
    app.kubernetes.io/instance: aws-code-pipeline-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: aws-code-pipeline
spec:
  selector:
    app: aws-code-pipeline
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80