version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:  
    commands: 
      - echo Starting pre-build phase
      - java -version
  build:
    commands:
      - echo Build started on `date`
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - ls
      - ls target/surefire-reports
artifacts:
  files:
    - target/aws-code-pipeline*.jar
    - appspec.yml
    - ecs-appspec.yml
    - taskdef.json
    - docker_buildspec.yml
    - Dockerfile
    - scripts/*
  discard-paths: yes