version: 0.2
phases:
  pre_build:  
    commands: 
      - echo Building docker image for the application
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 279522866734.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the docker image in build phase 
      - ls
      - docker build -t aws-code-pipeline:latest .
      - docker tag aws-code-pipeline:latest 279522866734.dkr.ecr.us-east-1.amazonaws.com/packt-ecr-repo:aws-code-pipeline  
  post_build:
    commands:
      - echo Pushing docker image to the ECR recpository completed on `date`
      - docker push 279522866734.dkr.ecr.us-east-1.amazonaws.com/packt-ecr-repo:aws-code-pipeline 
      - ls
artifacts:
  files:
    - appspec.yml
    - ecs-appspec.yml
    - taskdef.json
    - scripts/*
  discard-paths: yes