version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
file_exists_behavior: OVERWRITE
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  ApplicationStart:
    - location: start.sh
      timeout: 100
      runas: ec2-user
  ApplicationStop:
    - location: stop.sh
      timeout: 100
      runas: ec2-user