version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:  
    commands: 
      - echo Starting pre-build phase
      - java -version
  build:
    commands:
      - echo Build started on `date`
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - ls
      - ls target/surefire-reports
reports:
  arn:aws:codebuild:us-east-1:279522866734:report-group/aws-code-deploy-test-report:
    base-directory: 'target/surefire-reports'
    files:  
        - TEST-com.packt.aws.books.pipeline.AwsCodePipelineApplicationTests.xml
    discard-paths: yes
    file-format: JUNITXML
artifacts:
  files:
    - target/aws-code-pipeline*.jar
    - appspec.yml
    - scripts/*
  discard-paths: yes