version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:279522866734:task-definition/chap_10_task_definition:4"
        LoadBalancerInfo:
          ContainerName: "chap_10_aws_code_pipeline_container"
          ContainerPort: 80