apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: aws-code-pipeline
  name: aws-code-pipeline
spec:
  selector:
    app: aws-code-pipeline
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80